### ISSUE TITLE
Update projections and test uploading

### ISSUE THREAD

**Issue by Murilodsv** [cemac/AgroClimatic-Monitor#15]
I need to update raster projections to EPSG:3857 and test uploading via the uploading link (send email to Dan before uploading).

**Comment by Murilodsv** [comment]
Marcelo Zeri has updated all raster files with EPSG:3857 projection in folder raster3857 of [gdrive](https://drive.google.com/drive/folders/1-YXWD1RPXxQ_U4h4I79F2KmxbGyyEGzH?usp=sharing)

We still need to test the "uploading feature"

**Comment by Murilodsv** [comment]
Hi @cemachelen I just uploaded few .tif files for testing. It seems the uploading was successful!

I wonder how long would it take for this images to be updated on the corresponding pages? Is there a scheduled job for handling new data?

![image](https://user-images.githubusercontent.com/16140093/150491523-bafec675-b4cd-47b4-9b48-fa0e7ddebcd6.png)

**Comment by cemachelen** [comment]
@Murilodsv  I'll set up a cron job. I don't think anything is currently running. should I set it up to check daily?

**Comment by Murilodsv** [comment]
Thanks @cemachelen, a daily cron job should do. 

Please let us know as soon as possible which filename format should we use while uploading. For example:  `<indexname>_<year>_<month>.tif`?

Also note that we should add all the missing months until the release.

**Comment by Murilodsv** [comment]
Hi @cemachelen ,

It's really important that all the data is updated until tomorrow. Marcelo has uploaded the data for 2021 during the weekend, but it doesnt seem be updated in the app. 

Can you please confirm if its possible to get this updated until tomorrow?

Here's the 2021 data:
https://drive.google.com/drive/folders/12X1kx6UrWzwIlZdrqSQUXfpPEAXWVcnI?usp=sharing

Cheers

**Comment by cemachelen** [comment]
Hi @Murilodsv  This is running now. Sorry I think an email I sent last week just stayed in my drafts. I held off setting the cron job process until the preprocessing scripts were corrected.  I've now created a script to grab the new tif files and preprocess them. This currently running now. I'll let you know when its complete.

**Comment by cemachelen** [comment]
@Murilodsv all done now. Sorry for delay I had to alter the code to pick up the RZSM data. I hadn't noticed that was tiff data reading was throwing an error.  

SPI03 and SPI06 are missing some data though?

**Comment by Murilodsv** [comment]
No worries, I'll ask Marcelo and Ana to provide the missing data for SPI03 and 06 in 2020.

I noticed the individuals tab are again stuck in "Computing data..." status. Is it because the data is yet being processed for all municipalities?

**Comment by cemachelen** [comment]
@Murilodsv  should all be working now. I was just making some adjustments to make the site more stable (there's a minor configuration issue IT need to adjust but I'll ask for that fix after tomorrow's launch)
