### ISSUE TITLE
Maps formating

### ISSUE THREAD

**Issue by Murilodsv** [cemac/AgroClimatic-Monitor#2]
Here's some guidelines to improve the map shown in the "Data Browser" and "Indicator Maps":

![image](https://user-images.githubusercontent.com/16140093/111992867-d0de5700-8b0d-11eb-8e45-5bfc8787208d.png)

1) As briefly described in issue https://github.com/cemac/CSSP-Brazil/issues/1, the colour pallete should follow the pattern given in the [about the tool](https://docs.google.com/document/d/1Vg_mEmAr4P-WyQ2pOZzwse0f7IqpcxOKioHX5s_5R_w/edit?usp=sharing) outline. 

2) Maps are still a bit offset from the base shapefile contours (not only the RZSM)

3) Date and time should not be shown in the Atlantic, perhaps in the header just after the municipality name. Also it should be as  MM-YYYY.

4) Accented characters should be corrected for the municipalities names (perhaps an encoding='utf-8' may solve)

5) The pallete colours of hovering circles should change as they might mislead the users to think one index is "stronger or wearker" than others

6) The buttons should be more visible to users.

7) A more minor point: it can be hard to scroll down using the thumbwheel, since the map simply zooms. the outer limit of zoom is too big also.

**Comment by wolfiex** [comment]
GDAL projections not available for re-projecting maps. Install problem. 

Additionally original image projection unknown.

**Comment by wolfiex** [comment]
MAPS to be uploaded with EPSG:3857 formatting
