### ISSUE TITLE
Med Priority: Download current image not fully functional

### ISSUE THREAD

**Issue by cemachelen** [cemac/AgroClimatic-Monitor#40]
In https://agclimatebr.leeds.ac.uk/en/databrowser :

The quality of image downloaded when clicking in “Download Current Image” is poor and most importantly there is no territorial borders:

- This map needs the Brazilian States borders overlayed so that users have a geospatial reference.
You can find the shapefile (BR_EST_WGS84.*) or if easier the PNG for this in: https://drive.google.com/drive/folders/14bqdtfkNwvniC2wwZYdMQPMIqGr9A3Ur

- Could you please improve the resolution so that the dates are not too blurry in both the web browser and output image?

**Comment by cemachelen** [comment]
@Murilodsv  I've added a download PNG button to top right of the map and altered the base map, to a better resolution map showing the state boarders. Let me know how it is? other wise I'll rescale your boarders png and add that

**Comment by Murilodsv** [comment]
Thanks @cemachelen, now both the map in the app and downloaded png (printed) seems to have a white-transparent layer overlapping them. Can you make the colors more vivid at it was before but keeping the printing button with the boarders?

**Comment by cemachelen** [comment]
@Murilodsv  how does that look now? I'd decrease opacity to allow the map underneath to be seen better, but i've set it back to what it was now

**Comment by Murilodsv** [comment]
Thanks! The colors look better now, but the month-year resolution in top-right corner should be improved too.

**Comment by Murilodsv** [comment]
I think the maps are good now, so I'm closing this issue
