### ISSUE TITLE
all page titles and buttons in english regardless of lng selections

### ISSUE THREAD

**Issue by cemachelen** [cemac/AgroClimatic-Monitor#43]
pass through Portuguese titles and buttons. 

* copyright 
* data browsers subtitles
* index map subtitles
* Months on selector
* change the language

**Comment by Murilodsv** [comment]
---

Please, also translate the page titles (top of the page) on the following:
- "Welcome" on the homepage to "Bem vindo"
- "Using the tool" on the using the tool page to "Usando a ferramenta"
- "Disclaimer" on the disclaimer page to "Informação Legal"

---

The individual page should be translated completely. The english version also need minor correction. Please replace the texts below in EN and PT versions:

EN:
"Chart Description

The two graph below show the scaled indices represented within its own drought category. The averaged value for each index is showed whilst moving the cursor over the chart.

The top graph displays the timeseries of VHI, SPI, RZSM and IDI, where the SPI is the average of all SPI 1, SPI 3, SPI 6 and SPI 12. The bottom graph displays all the SPI indices individually."

PT:
"Descrição do gráfico

Os dois gráficos abaixo mostram os índices em escala representados dentro de sua própria categoria de seca. O valor médio de cada índice é mostrado ao mover o cursor sobre o gráfico.

O gráfico superior exibe as séries temporais de VHI, SPI, RZSM e IDI, onde o SPI é a média de todos os valores de SPI 1, SPI 3, SPI 6 e SPI 12. O gráfico inferior exibe todos os índices SPI individualmente."

---

In the PT version, remove the "e" from the change language title:

![image](https://user-images.githubusercontent.com/16140093/151671920-95cf51be-4d8a-4ad1-b730-b7e82695a84b.png)

---

**Comment by cemachelen** [comment]
This is mostly done. Double checking Index Plots -->  Gráficos de índice ?

**Comment by Murilodsv** [comment]
Yes, "Gráficos de índice" is good. Thanks.
