### ISSUE TITLE
Timeout / unmount issue for uolstorage

### ISSUE THREAD

**Issue by wolfiex** [cemac/AgroClimatic-Monitor#5]
@Murilodsv It is probably worth asking IT how to proceed. The drive mount requires periodic kerberos re-initation using `kinit`. Clearly this is very impractical for a persistent system.

@MarkUoLeeds  any suggestions?

**Comment by Murilodsv** [comment]
Thanks @wolfiex,

does it mean our storage is periodically unmounted? I'll ask them to look at it for you.

**Comment by MarkUoLeeds** [comment]
If you mean that the research storage system becomes unmounted from the VM then perhaps the kerberos suggestion will work?
I did not know this was happening for the VM. Or is this to do with accessing research storage from other campus systems?

Mark

**Comment by wolfiex** [comment]
Yes @MarkUoLeeds, @cemacrr's suggestion should work as a jury rig of the system. 

The main problem now is that we need: 
- A project username for the VM (such that it runs on a user space accessible to everyone on the team
- A set of credentials to remount the drive periodically as using the commands below. 


@Murilodsv 

#
### Commands

```
   $ mkdir ~/.krb5
      $ chmod 700 ~/.krb5
      $ cd ~/.krb5
      $ ktutil
      ktutil:  addent -password -p xxxx@DS.LEEDS.AC.UK -k 1 -e aesxxx-cts
      Password for xxxx@DS.LEEDS.AC.UK:
      ktutil:  wkt earrr.keytab
      ktutil:  q
```

#### This would create the keytab file within my home directory at:

   `  ~/.krb5/xxxx.keytabz`

### No error:
`kinit -k -t earrr.keytab xxxx@DS.LEEDS.AC.UK`

#### Cron 15 m 
```   
*/15 * * * * kinit -k -t ~/.krb5/earrr.keytab earrr@DS.LEEDS.AC.UK >& /dev/null && \ls /nfs/earcemac >& /dev/null
```

**Comment by Murilodsv** [comment]
Thanks for providing more details, @wolfiex . I've just asked IT if they can assist us with these two bullet points, or if they have another solution. Keep you posted.

**Comment by Murilodsv** [comment]
Hi @wolfiex,

IT might be able to get a kerberos keytab created for our project.
Keep you posted.

**Comment by Murilodsv** [comment]
IT has just replied the kerberos request:

==================================================================
 
Please could you supply me with the full path of the storage area which you are trying to access when you experience the problem with Kerberos expiring. This information is needed for us to create the username that will go into the keytab.

==================================================================

@wolfiex, can you please confirm the full path of the storage area you are facing this issue? I guess it would be /nfs/b0139?

Thanks!
Murilo

**Comment by MarkUoLeeds** [comment]
Hello Murilo et al,
I think this project VM needs an additonal useid where any one of Marcelo, Murilo or Dan can SSH into the a local account but it will also need to have kerberos credentials to see the network storage.

I find it challenging that IT keep doing this to you.
 I can understand that they want "us" to be clear when specifying these complex issues but they ought to offer some guidance on what might be best practice.

**Comment by Murilodsv** [comment]
I understand this issue was already addressed at this point.
